// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHWcbMk4JGiM4_KRdD99T_5kPGpXDg5G4',
    appId: '1:1047386374539:web:9b617bdf3851ea525a6f8e',
    messagingSenderId: '1047386374539',
    projectId: 'vaccenily',
    authDomain: 'vaccenily.firebaseapp.com',
    databaseURL: 'https://vaccenily-default-rtdb.firebaseio.com',
    storageBucket: 'vaccenily.appspot.com',
    measurementId: 'G-Q7JTVX3CB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbU39QBD1Y20QReG9wC0TQ50JIMLylWrA',
    appId: '1:1047386374539:android:8194fbd2e6e74b285a6f8e',
    messagingSenderId: '1047386374539',
    projectId: 'vaccenily',
    databaseURL: 'https://vaccenily-default-rtdb.firebaseio.com',
    storageBucket: 'vaccenily.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSMzw_ML3VDAENqg1x9k8xoTjQeJrr92Q',
    appId: '1:1047386374539:ios:d3d99fb287074a475a6f8e',
    messagingSenderId: '1047386374539',
    projectId: 'vaccenily',
    databaseURL: 'https://vaccenily-default-rtdb.firebaseio.com',
    storageBucket: 'vaccenily.appspot.com',
    iosClientId: '1047386374539-ugda0g7r3i65ovmrrsfpin34un9jv320.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashborad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSMzw_ML3VDAENqg1x9k8xoTjQeJrr92Q',
    appId: '1:1047386374539:ios:d3d99fb287074a475a6f8e',
    messagingSenderId: '1047386374539',
    projectId: 'vaccenily',
    databaseURL: 'https://vaccenily-default-rtdb.firebaseio.com',
    storageBucket: 'vaccenily.appspot.com',
    iosClientId: '1047386374539-ugda0g7r3i65ovmrrsfpin34un9jv320.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashborad',
  );
}
